# Generated by Django 6.0 on 2025-12-21 19:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pseudo', models.CharField(db_index=True, max_length=50)),
                ('points', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('predicted_temp_pi1', models.FloatField(blank=True, null=True)),
                ('predicted_temp_pi2', models.FloatField(blank=True, null=True)),
                ('predicted_temp_pi3', models.FloatField(blank=True, null=True)),
                ('max_temp_pi1', models.FloatField(blank=True, null=True)),
                ('max_temp_pi2', models.FloatField(blank=True, null=True)),
                ('max_temp_pi3', models.FloatField(blank=True, null=True)),
                ('prompt', models.TextField()),
                ('answer_pi1', models.TextField(blank=True, null=True)),
                ('answer_pi2', models.TextField(blank=True, null=True)),
                ('answer_pi3', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-points', 'created_at'],
                'indexes': [models.Index(fields=['-points', 'created_at'], name='dashboard_l_points_32fc75_idx'), models.Index(fields=['pseudo', '-points'], name='dashboard_l_pseudo_c1935d_idx')],
            },
        ),
    ]
